Implement phone mask
greenriver/hmis-frontend pull request #426
Opened 2023-08-25 21:44 UTC by ZachCMP

https://www.pivotaltracker.com/story/show/185740385

2023-08-28 12:21 UTC, gigxz requested changes
Looks like some phone numbers aren't being displayed on the read-only view. Can you update that to be more permissive? It can continue to apply formatting, but if the phone string doesn't match the expected legnth/chars, we should still display it as-is. We shouldn't be hiding any data.

<img width="625" alt="Screen Shot 2023-08-28 at 8 19 39 AM" src="https://github.com/greenriver/hmis-frontend/assets/5333982/89ceb67a-1ad6-4085-aceb-2381a7722042">
<img width="925" alt="Screen Shot 2023-08-28 at 8 19 29 AM" src="https://github.com/greenriver/hmis-frontend/assets/5333982/7fb712e9-7b3d-43ca-a200-8de8837f7df9">

2023-08-28 12:21 UTC, gigxz commented on src/components/elements/input/PhoneInput.tsx
> +            mask: '{+}0` (000) 000-0000',
Can you update this to allow 2 digits for country code?

2023-08-28 12:23 UTC, gigxz commented
Oh, I just realized that the numbers are actually being persisted in the db with the special characters, like `value: "+1 (802) 999-1111"`. I think we should only store the numeric values, and just use the input mask for display purposes. That gives us more flexibility as to how we display them, and makes the data cleaner for export purposes if needed.

2023-08-28 20:44 UTC, ZachCMP commented
@gigxz Addressed your feedback. I set it to allow for 2 country codes and also switched the logic to display phone numbers to use the same IMask formatter as the inputs rather than the regex mechanism that was being used before. That should make the input/display of phone numbers consistent.

2023-08-29 15:08 UTC, gigxz approved these changes
This looks good, thanks! It still could be more forgiving to display malformed phone numbers, so I'm pushing a fix for that.

2023-08-29 15:37 UTC, merged